import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { ThemeProvider } from "@/providers/theme-provider";
import "../assets/styles/globals.css";
import type { Metadata } from "next";
import { cn } from "@/utils/cn";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps extends PropsWithChildren {}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={cn(GeistSans.className, GeistMono.variable)}>
      <body
        className={cn(
          "text-black bg-white dark:text-white dark:bg-[#111010]",
          "max-w-2xl mb-40 lg:mx-auto mx-4 mt-8",
          "flex flex-col md:flex-row",
          "scroll-smooth tracking-[.05em] antialiased font-sans"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main
            className={cn(
              "flex-auto flex flex-col",
              "min-w-0 mt-6 px-2 md:px-0"
            )}
          >
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
