import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { ThemeProvider } from "@/providers/theme-provider";
import "../assets/styles/globals.css";
import type { Metadata } from "next";
import { cn } from "@/utils/cn";
import { PropsWithChildren } from "react";
import Footer from "@/layouts/footer";
import Header from "@/layouts/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps extends PropsWithChildren {}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(GeistSans.className, GeistMono.variable)}
    >
      <head />
      <body
        className={cn(
          "text-black bg-white dark:text-white dark:bg-[#111010]",
          "scroll-smooth tracking-[.05em] antialiased font-sans"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div
            className={cn(
              "max-w-2xl mx-auto min-h-screen",
              "flex flex-col shrink-0",
              "p-4"
            )}
          >
            <Header />
            <main className={cn("flex-auto", "p-4 my-2")}>{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
